#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-sphinx_design
Version  : 0.0.13
Release  : 4
URL      : https://files.pythonhosted.org/packages/44/6d/0b36d5fa3c422288bfd1ff28f4f98df9fb36b31e072c19a275f759876c62/sphinx_design-0.0.13.tar.gz
Source0  : https://files.pythonhosted.org/packages/44/6d/0b36d5fa3c422288bfd1ff28f4f98df9fb36b31e072c19a275f759876c62/sphinx_design-0.0.13.tar.gz
Summary  : A sphinx extension for designing beautiful, view size responsive web components.
Group    : Development/Tools
License  : MIT
Requires: pypi-sphinx_design-license = %{version}-%{release}
Requires: pypi-sphinx_design-python = %{version}-%{release}
Requires: pypi-sphinx_design-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(importlib_resources)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(sphinx)
BuildRequires : pypi(wheel)

%description
[![Github-CI][github-ci]][github-link]
        [![Coverage Status][codecov-badge]][codecov-link]
        [![PyPI][pypi-badge]][pypi-link]
        
        A sphinx extension for designing beautiful, view size responsive web components.

%package license
Summary: license components for the pypi-sphinx_design package.
Group: Default

%description license
license components for the pypi-sphinx_design package.


%package python
Summary: python components for the pypi-sphinx_design package.
Group: Default
Requires: pypi-sphinx_design-python3 = %{version}-%{release}

%description python
python components for the pypi-sphinx_design package.


%package python3
Summary: python3 components for the pypi-sphinx_design package.
Group: Default
Requires: python3-core
Provides: pypi(sphinx_design)
Requires: pypi(importlib_resources)
Requires: pypi(sphinx)

%description python3
python3 components for the pypi-sphinx_design package.


%prep
%setup -q -n sphinx_design-0.0.13
cd %{_builddir}/sphinx_design-0.0.13

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641587348
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-sphinx_design
cp %{_builddir}/sphinx_design-0.0.13/LICENSE %{buildroot}/usr/share/package-licenses/pypi-sphinx_design/f341f3903e7e7e8c1e0369a22921ff11c1ef261d
cp %{_builddir}/sphinx_design-0.0.13/sphinx_design/compiled/octicon_LICENSE %{buildroot}/usr/share/package-licenses/pypi-sphinx_design/5c0e418ff5750461e481972fdc40ecb88ce84b26
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-sphinx_design/5c0e418ff5750461e481972fdc40ecb88ce84b26
/usr/share/package-licenses/pypi-sphinx_design/f341f3903e7e7e8c1e0369a22921ff11c1ef261d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
